
problem master;

if DISPLAY_MASTER_SOLVE == 1 then{
#	option solver_msg 1;
#	option cplex_options 'outlev=1 lpdisplay=2';
	solve MASTER_OBJ;
}else{
	close master.log;
	solve MASTER_OBJ > master.log;
};
#printf "master solve took %20d\n", time()-M_TIME;
if solve_result != 'solved' then exit;

let{v in V} DUAL_FOR_RC[v] := set_partitionning[v].dual;


let CG_BOUND := sum{col in COLS}COST[col]*x[col];

let POOL_COST := {};
let POOL_SOLUTION  := {};
let STEP := "UNKNOWN";



