
let STEP := "HEUR";
problem slave_exact;
let HEUR_NUM := 0;

# 2-uple
for{v1 in V, v2 in V: v1<v2}{	
	let{v in V} y[v]:= if v in {v1, v2} then 1 else 0;
	if reduced_cost_y > ZERO_REDUCED_COST then {
		let HEUR_NUM := HEUR_NUM+1;
		let POOL_COST := POOL_COST union {(HEUR_NUM, slave_cost_y, reduced_cost_y)};
		let POOL_SOLUTION := POOL_SOLUTION union setof{__v in V: y[__v] > 0.5}(HEUR_NUM, __v);
	};	
};